# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=36, verbose_name='Offer')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
            ],
            options={
                'verbose_name_plural': 'OfferSales',
                'db_table': 'offer_sale',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=36, verbose_name='Code')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name_plural': 'Stocks',
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=36, verbose_name='Code')),
                ('date', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('01', 'SUCCESS'), ('02', 'REJECT')], default='01', max_length=2, verbose_name='State')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'db_table': 'transaction',
            },
        ),
        migrations.AddField(
            model_name='offersale',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='stock.Transaction'),
        ),
    ]
